### ISSUE TITLE
Task creation fails with long list of metrics from different collectors

### ISSUE THREAD

**Issue by juliasantos** [intelsdi-x/snap#1073]
I have a list of metrics from 3 different collectors that I want to combine into one output file. I first created 3 different task files (one for each collector) that wrote to 3 separate output files to test and make sure everything worked. Then I made a combined task file that would write to one output file. Even though the 3 individual tasks worked fine, the combined task fails with a runtime error.  I've attached files with the errors, the 3 individual task files, and the combined file. I couldn't attach the json task files directly, let me know if there is a better way to provide them (I changed them to txt).

[snap_task_errors.txt](https://github.com/intelsdi-x/snap/files/364939/snap_task_errors.txt)

[disk-file_linux.txt](https://github.com/intelsdi-x/snap/files/365231/disk-file_linux.txt)
[iostat-file_linux.txt](https://github.com/intelsdi-x/snap/files/365232/iostat-file_linux.txt)
[psutil-file_linux.txt](https://github.com/intelsdi-x/snap/files/365233/psutil-file_linux.txt)
[select_telem_file_pub.txt](https://github.com/intelsdi-x/snap/files/365234/select_telem_file_pub.txt)

**Comment by lynxbat** [comment]
Using gist.github.com is a great way to share these. Also you can inline json into these issues (using Markdown).

Here is the data:

Error:
```
====TERMINAL WHERE I RUN TASK CREATION====
[jasantos@dia-aaron-00 plugins]$ snapctl task create -t ../select_telem_file_pub.json
Using task manifest to create task
Error creating task:
Unknown API response: invalid character 'P' looking for beginning of value

 Received: PANIC: runtime error: index out of range
goroutine 2990 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x7ff93a23bb30, 0xc820114240, 0xc820229a80)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/recovery.go:34 +0xe9
panic(0xb98020, 0xc82000e0b0)
        /gonative/go/src/runtime/panic.go:443 +0x4e9
github.com/intelsdi-x/snap/pkg/ctree.(*ConfigTree).Get(0xc8200c9b00, 0xc820014b80, 0x5, 0x8, 0x0, 0x0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/pkg/ctree/tree.go:167 +0x12cb
github.com/intelsdi-x/snap/core/cdata.(*ConfigDataTree).Get(0xc820022040, 0xc820014b80, 0x5, 0x8, 0x5)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/core/cdata/tree.go:69 +0x6a
github.com/intelsdi-x/snap/scheduler.(*scheduler).gatherMetricsAndPlugins(0xc82020b580, 0xc820014600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/scheduler/scheduler.go:604 +0x3b9
github.com/intelsdi-x/snap/scheduler.(*scheduler).createTask(0xc82020b580, 0x7ff93a

====SNAPD TERMINAL RESULTS====
INFO[2919] API request                                   _module=_mgmt-rest index=11 method=POST url=/v1/tasks
[negroni] PANIC: runtime error: index out of range
goroutine 2990 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x7ff93a23bb30, 0xc820114240, 0xc820229a80)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/recovery.go:34 +0xe9
panic(0xb98020, 0xc82000e0b0)
        /gonative/go/src/runtime/panic.go:443 +0x4e9
github.com/intelsdi-x/snap/pkg/ctree.(*ConfigTree).Get(0xc8200c9b00, 0xc820014b80, 0x5, 0x8, 0x0, 0x0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/pkg/ctree/tree.go:167 +0x12cb
github.com/intelsdi-x/snap/core/cdata.(*ConfigDataTree).Get(0xc820022040, 0xc820014b80, 0x5, 0x8, 0x5)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/core/cdata/tree.go:69 +0x6a
github.com/intelsdi-x/snap/scheduler.(*scheduler).gatherMetricsAndPlugins(0xc82020b580, 0xc820014600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/scheduler/scheduler.go:604 +0x3b9
github.com/intelsdi-x/snap/scheduler.(*scheduler).createTask(0xc82020b580, 0x7ff93a246868, 0xc8200c9aa0, 0xc820022028, 0x1, 0xc96500, 0x4, 0xc820022038, 0x1, 0x1, ...)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/scheduler/scheduler.go:207 +0xe16
github.com/intelsdi-x/snap/scheduler.(*scheduler).CreateTask(0xc82020b580, 0x7ff93a246868, 0xc8200c9aa0, 0xc820022028, 0x1, 0xc820022038, 0x1, 0x1, 0x0, 0x0, ...)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/scheduler/scheduler.go:163 +0xb8
github.com/intelsdi-x/snap/mgmt/rest.(*Server).addTask(0xc8200e51e0, 0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0x0, 0x0, 0x0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/mgmt/rest/task.go:100 +0x528
github.com/intelsdi-x/snap/mgmt/rest.(*Server).(github.com/intelsdi-x/snap/mgmt/rest.addTask)-fm(0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0x0, 0x0, 0x0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/mgmt/rest/server.go:433 +0x5c
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc8201ed950, 0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/julienschmidt/httprouter/router.go:299 +0x193
github.com/codegangsta/negroni.Wrap.func1(0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e01e0)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:41 +0x50
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc820229b20, 0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e01e0)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:24 +0x44
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7ff93a23a6d0, 0xc820229b20, 0xc820229ba0, 0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/intelsdi-x/snap/mgmt/rest.(*Server).authMiddleware(0xc8200e51e0, 0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e01c0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/mgmt/rest/server.go:304 +0x191
github.com/intelsdi-x/snap/mgmt/rest.(*Server).(github.com/intelsdi-x/snap/mgmt/rest.authMiddleware)-fm(0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e01c0)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/mgmt/rest/server.go:205 +0x48
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc82022ae30, 0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e01c0)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:24 +0x44
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7ff93a23a6d0, 0xc82022ae30, 0xc820229b80, 0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc820229a80, 0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e01a0)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/recovery.go:45 +0x75
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7ff93a23a6a8, 0xc820229a80, 0xc820229b60, 0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/intelsdi-x/snap/mgmt/rest.(*Logger).ServeHTTP(0xc82022ae20, 0x7ff93a23bb30, 0xc820114240, 0xc820094000, 0xc8200e0120)
        /snapbuild/build/snap/src/github.com/intelsdi-x/snap/mgmt/rest/log_handler.go:46 +0x387
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7ff93a23a680, 0xc82022ae20, 0xc820229b40, 0x7ff93a23bb30, 0xc820114240, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc8201ed920, 0x7ff93a23ba98, 0xc8200fc410, 0xc820094000)
        /snapbuild/build/snap/src/github.com/codegangsta/negroni/negroni.go:73 +0x122
net/http.serverHandler.ServeHTTP(0xc820163b80, 0x7ff93a23ba98, 0xc8200fc410, 0xc820094000)
        /gonative/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820014100)
        /gonative/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /gonative/go/src/net/http/server.go:2137 +0x44e
INFO[2919] API response                                  _module=_mgmt-rest index=11 method=POST status=Internal Server Error status-code=500 url=/v1/tasks
```

disk-file_linux
```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
		"/intel/procfs/disk/*/io_time": {},
		"/intel/procfs/disk/*/merged_read": {},                
		"/intel/procfs/disk/*/merged_write": {}, 
		"/intel/procfs/disk/*/octets_read": {},
		"/intel/procfs/disk/*/octets_write": {},
		"/intel/procfs/disk/*/ops_read": {},
		"/intel/procfs/disk/*/ops_write": {},
		"/intel/procfs/disk/*/pending_ops": {},
		"/intel/procfs/disk/*/time_read": {},
		"/intel/procfs/disk/*/time_write": {},
		"/intel/procfs/disk/*/weighted_io_time": {}
	    },
            "config": {
                "/intel/procfs/disk": {
                    "proc_path": "/proc"
                }
            },
            "process": [
                {
                    "plugin_name": "passthru",
                    "process": null,
                    "publish": [
                        {                         
                            "plugin_name": "file",
			    "version": 1,
                            "config": {
                                "file": "/home/jasantos/procfs_disk_all.json"
                            }
                        }
                    ],
                    "config": null
                }
            ],
            "publish": null
        }
    }
}
```

iostat-file_linux
```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
		"/intel/linux/iostat/avg-cpu/%idle": {},
		"/intel/linux/iostat/avg-cpu/%iowait": {},
		"/intel/linux/iostat/avg-cpu/%nice": {},
		"/intel/linux/iostat/avg-cpu/%steal": {},
		"/intel/linux/iostat/avg-cpu/%system": {},
		"/intel/linux/iostat/avg-cpu/%user": {},
		"/intel/linux/iostat/device/ALL/%util": {},
		"/intel/linux/iostat/device/ALL/avgqu-sz": {},
		"/intel/linux/iostat/device/ALL/avgrq-sz": {},
		"/intel/linux/iostat/device/ALL/await": {},
		"/intel/linux/iostat/device/ALL/r_await": {},
		"/intel/linux/iostat/device/ALL/r_per_sec": {},
		"/intel/linux/iostat/device/ALL/rkB_per_sec": {},
		"/intel/linux/iostat/device/ALL/rrqm_per_sec": {},
		"/intel/linux/iostat/device/ALL/svctm": {},
		"/intel/linux/iostat/device/ALL/w_await": {},
		"/intel/linux/iostat/device/ALL/w_per_sec": {},
		"/intel/linux/iostat/device/ALL/wkB_per_sec": {},
		"/intel/linux/iostat/device/ALL/wrqm_per_sec": {},
		"/intel/linux/iostat/device/dm-0/%util": {},
		"/intel/linux/iostat/device/dm-0/avgqu-sz": {},
		"/intel/linux/iostat/device/dm-0/avgrq-sz": {},
		"/intel/linux/iostat/device/dm-0/await": {},
		"/intel/linux/iostat/device/dm-0/r_await": {},
		"/intel/linux/iostat/device/dm-0/r_per_sec": {},
		"/intel/linux/iostat/device/dm-0/rkB_per_sec": {},
		"/intel/linux/iostat/device/dm-0/rrqm_per_sec": {},
		"/intel/linux/iostat/device/dm-0/svctm": {},
		"/intel/linux/iostat/device/dm-0/w_await": {},
		"/intel/linux/iostat/device/dm-0/w_per_sec": {},
		"/intel/linux/iostat/device/dm-0/wkB_per_sec": {},
		"/intel/linux/iostat/device/dm-0/wrqm_per_sec": {},
		"/intel/linux/iostat/device/dm-1/%util": {},
		"/intel/linux/iostat/device/dm-1/avgqu-sz": {},
		"/intel/linux/iostat/device/dm-1/avgrq-sz": {},
		"/intel/linux/iostat/device/dm-1/await": {},
		"/intel/linux/iostat/device/dm-1/r_await": {},
		"/intel/linux/iostat/device/dm-1/r_per_sec": {},
		"/intel/linux/iostat/device/dm-1/rkB_per_sec": {},
		"/intel/linux/iostat/device/dm-1/rrqm_per_sec": {},
		"/intel/linux/iostat/device/dm-1/svctm": {},
		"/intel/linux/iostat/device/dm-1/w_await": {},
		"/intel/linux/iostat/device/dm-1/w_per_sec": {},
		"/intel/linux/iostat/device/dm-1/wkB_per_sec": {},
		"/intel/linux/iostat/device/dm-1/wrqm_per_sec": {},
		"/intel/linux/iostat/device/dm-2/%util": {},
		"/intel/linux/iostat/device/dm-2/avgqu-sz": {},
		"/intel/linux/iostat/device/dm-2/avgrq-sz": {},
		"/intel/linux/iostat/device/dm-2/await": {},
		"/intel/linux/iostat/device/dm-2/r_await": {},
		"/intel/linux/iostat/device/dm-2/r_per_sec": {},
		"/intel/linux/iostat/device/dm-2/rkB_per_sec": {},
		"/intel/linux/iostat/device/dm-2/rrqm_per_sec": {},
		"/intel/linux/iostat/device/dm-2/svctm": {},
		"/intel/linux/iostat/device/dm-2/w_await": {},
		"/intel/linux/iostat/device/dm-2/w_per_sec": {},
		"/intel/linux/iostat/device/dm-2/wkB_per_sec": {},
		"/intel/linux/iostat/device/dm-2/wrqm_per_sec": {},
		"/intel/linux/iostat/device/sda/%util": {},
		"/intel/linux/iostat/device/sda/avgqu-sz": {},
		"/intel/linux/iostat/device/sda/avgrq-sz": {},
		"/intel/linux/iostat/device/sda/await": {},
		"/intel/linux/iostat/device/sda/r_await": {},
		"/intel/linux/iostat/device/sda/r_per_sec": {},
		"/intel/linux/iostat/device/sda/rkB_per_sec": {},
		"/intel/linux/iostat/device/sda/rrqm_per_sec": {},
		"/intel/linux/iostat/device/sda/svctm": {},
		"/intel/linux/iostat/device/sda/w_await": {},
		"/intel/linux/iostat/device/sda/w_per_sec": {},
		"/intel/linux/iostat/device/sda/wkB_per_sec": {},
		"/intel/linux/iostat/device/sda/wrqm_per_sec": {},
		"/intel/linux/iostat/device/sda1/%util": {},
		"/intel/linux/iostat/device/sda1/avgqu-sz": {},
		"/intel/linux/iostat/device/sda1/avgrq-sz": {},
		"/intel/linux/iostat/device/sda1/await": {},
		"/intel/linux/iostat/device/sda1/r_await": {},
		"/intel/linux/iostat/device/sda1/r_per_sec": {},
		"/intel/linux/iostat/device/sda1/rkB_per_sec": {},
		"/intel/linux/iostat/device/sda1/rrqm_per_sec": {},
		"/intel/linux/iostat/device/sda1/svctm": {},
		"/intel/linux/iostat/device/sda1/w_await": {},
		"/intel/linux/iostat/device/sda1/w_per_sec": {},
		"/intel/linux/iostat/device/sda1/wkB_per_sec": {},
		"/intel/linux/iostat/device/sda1/wrqm_per_sec": {},
		"/intel/linux/iostat/device/sda2/%util": {},
		"/intel/linux/iostat/device/sda2/avgqu-sz": {},
		"/intel/linux/iostat/device/sda2/avgrq-sz": {},
		"/intel/linux/iostat/device/sda2/await": {},
		"/intel/linux/iostat/device/sda2/r_await": {},
		"/intel/linux/iostat/device/sda2/r_per_sec": {},
		"/intel/linux/iostat/device/sda2/rkB_per_sec": {},
		"/intel/linux/iostat/device/sda2/rrqm_per_sec": {},
		"/intel/linux/iostat/device/sda2/svctm": {},
		"/intel/linux/iostat/device/sda2/w_await": {},
		"/intel/linux/iostat/device/sda2/w_per_sec": {},
		"/intel/linux/iostat/device/sda2/wkB_per_sec": {},
		"/intel/linux/iostat/device/sda2/wrqm_per_sec": {}
	    },
            "config": {
                "/intel/linux/iostat": {
                    "ReportSinceBoot:": false
                }
            },
            "process": [
                {
                    "plugin_name": "passthru",
                    "process": null,
                    "publish": [
                        {                         
                            "plugin_name": "file",
			    "version": 1,
                            "config": {
                                "file": "/home/jasantos/iostat_all.json"
                            }
                        }
                    ],
                    "config": null
                }
            ],
            "publish": null
        }
    }
}
```

psutil-file_linux
```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/psutil/cpu0/guest": {},
		"/intel/psutil/cpu0/guest_nice": {},
		"/intel/psutil/cpu0/idle": {},
		"/intel/psutil/cpu0/iowait": {},
		"/intel/psutil/cpu0/irq": {},
		"/intel/psutil/cpu0/nice": {},
		"/intel/psutil/cpu0/softirq": {},
		"/intel/psutil/cpu0/steal": {},
		"/intel/psutil/cpu0/stolen": {},
		"/intel/psutil/cpu0/system": {},
		"/intel/psutil/cpu0/user": {},
		"/intel/psutil/load/load1": {},
		"/intel/psutil/load/load15": {},
		"/intel/psutil/load/load5": {},
		"/intel/psutil/net/all/bytes_recv": {},
		"/intel/psutil/net/all/bytes_sent": {},
		"/intel/psutil/net/all/dropin": {},
		"/intel/psutil/net/all/dropout": {},
		"/intel/psutil/net/all/errin": {},
		"/intel/psutil/net/all/errout": {},
		"/intel/psutil/net/all/packets_recv": {},
		"/intel/psutil/net/all/packets_sent": {},
		"/intel/psutil/net/eth0/bytes_recv": {},
		"/intel/psutil/net/eth0/bytes_sent": {},
		"/intel/psutil/net/eth0/dropin": {},
		"/intel/psutil/net/eth0/dropout": {},
		"/intel/psutil/net/eth0/errin": {},
		"/intel/psutil/net/eth0/errout": {},
		"/intel/psutil/net/eth0/packets_recv": {},
		"/intel/psutil/net/eth0/packets_sent": {},
		"/intel/psutil/net/eth1/bytes_recv": {},
		"/intel/psutil/net/eth1/bytes_sent": {},
		"/intel/psutil/net/eth1/dropin": {},
		"/intel/psutil/net/eth1/dropout": {},
		"/intel/psutil/net/eth1/errin": {},
		"/intel/psutil/net/eth1/errout": {},
		"/intel/psutil/net/eth1/packets_recv": {},
		"/intel/psutil/net/eth1/packets_sent": {},
		"/intel/psutil/net/lo/bytes_recv": {},
		"/intel/psutil/net/lo/bytes_sent": {},
		"/intel/psutil/net/lo/dropin": {},
		"/intel/psutil/net/lo/dropout": {},
		"/intel/psutil/net/lo/errin": {},
		"/intel/psutil/net/lo/errout": {},
		"/intel/psutil/net/lo/packets_recv": {},
		"/intel/psutil/net/lo/packets_sent": {},
		"/intel/psutil/net/virbr0-nic/bytes_recv": {},
		"/intel/psutil/net/virbr0-nic/bytes_sent": {},
		"/intel/psutil/net/virbr0-nic/dropin": {},
		"/intel/psutil/net/virbr0-nic/dropout": {},
		"/intel/psutil/net/virbr0-nic/errin": {},
		"/intel/psutil/net/virbr0-nic/errout": {},
		"/intel/psutil/net/virbr0-nic/packets_recv": {},
		"/intel/psutil/net/virbr0-nic/packets_sent": {},
		"/intel/psutil/net/virbr0/bytes_recv": {},
		"/intel/psutil/net/virbr0/bytes_sent": {},
		"/intel/psutil/net/virbr0/dropin": {},
		"/intel/psutil/net/virbr0/dropout": {},
		"/intel/psutil/net/virbr0/errin": {},
		"/intel/psutil/net/virbr0/errout": {},
		"/intel/psutil/net/virbr0/packets_recv": {},
		"/intel/psutil/net/virbr0/packets_sent": {},
		"/intel/psutil/vm/active": {},
		"/intel/psutil/vm/available": {},
		"/intel/psutil/vm/buffers": {},
		"/intel/psutil/vm/cached": {}
	    },
            "config": {
                "/intel/mock": {
                    "password": "secret",
                    "user": "root"
                }
            },
            "process": [
                {
                    "plugin_name": "passthru",
                    "process": null,
                    "publish": [
                        {                         
                            "plugin_name": "file",
			    "version": 1,
                            "config": {
                                "file": "/home/jasantos/psutil_all.json"
                            }
                        }
                    ],
                    "config": null
                }
            ],
            "publish": null
        }
    }
}
```

select_telem_file_pub-2
```json
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
		"/intel/psutil/cpu0/idle": {},
		"/intel/psutil/cpu0/iowait": {},
		"/intel/psutil/cpu0/irq": {},
		"/intel/psutil/cpu0/system": {},
		"/intel/psutil/cpu0/user": {},
		"/intel/psutil/load/load1": {},
		"/intel/psutil/load/load15": {},
		"/intel/psutil/load/load5": {},
		"/intel/psutil/net/all/bytes_recv": {},
		"/intel/psutil/net/all/bytes_sent": {},
		"/intel/psutil/net/all/errin": {},
		"/intel/psutil/net/all/errout": {},
		"/intel/psutil/net/all/packets_recv": {},
		"/intel/psutil/net/all/packets_sent": {},
		"/intel/psutil/net/eth0/bytes_recv": {},
		"/intel/psutil/net/eth0/bytes_sent": {},
		"/intel/psutil/net/eth0/errin": {},
		"/intel/psutil/net/eth0/errout": {},
		"/intel/psutil/net/eth0/packets_recv": {},
		"/intel/psutil/net/eth0/packets_sent": {},
		"/intel/psutil/net/eth1/bytes_recv": {},
		"/intel/psutil/net/eth1/bytes_sent": {},
		"/intel/psutil/net/eth1/errin": {},
		"/intel/psutil/net/eth1/errout": {},
		"/intel/psutil/net/eth1/packets_recv": {},
		"/intel/psutil/net/eth1/packets_sent": {},
		"/intel/psutil/net/lo/bytes_recv": {},
		"/intel/psutil/net/lo/bytes_sent": {},
		"/intel/psutil/net/lo/errin": {},
		"/intel/psutil/net/lo/errout": {},
		"/intel/psutil/net/lo/packets_recv": {},
		"/intel/psutil/net/lo/packets_sent": {},
		"/intel/psutil/net/virbr0-nic/bytes_recv": {},
		"/intel/psutil/net/virbr0-nic/bytes_sent": {},
		"/intel/psutil/net/virbr0-nic/errin": {},
		"/intel/psutil/net/virbr0-nic/errout": {},
		"/intel/psutil/net/virbr0-nic/packets_recv": {},
		"/intel/psutil/net/virbr0-nic/packets_sent": {},
		"/intel/psutil/net/virbr0/bytes_recv": {},
		"/intel/psutil/net/virbr0/bytes_sent": {},
		"/intel/psutil/net/virbr0/errin": {},
		"/intel/psutil/net/virbr0/errout": {},
		"/intel/psutil/net/virbr0/packets_recv": {},
		"/intel/psutil/net/virbr0/packets_sent": {},
		"/intel/psutil/vm/active": {},
		"/intel/psutil/vm/available": {},
		"/intel/psutil/vm/buffers": {},
		"/intel/psutil/vm/cached": {},
                "/intel/linux/iostat/device/ALL/%util": {},
                "/intel/linux/iostat/device/ALL/await": {},
                "/intel/linux/iostat/device/ALL/r_await": {},
                "/intel/linux/iostat/device/ALL/r_per_sec": {},
                "/intel/linux/iostat/device/ALL/rkB_per_sec": {},
                "/intel/linux/iostat/device/ALL/rrqm_per_sec": {},
                "/intel/linux/iostat/device/ALL/w_await": {},
                "/intel/linux/iostat/device/ALL/w_per_sec": {},
                "/intel/linux/iostat/device/ALL/wkB_per_sec": {},
                "/intel/linux/iostat/device/ALL/wrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-0/%util": {},
                "/intel/linux/iostat/device/dm-0/await": {},
                "/intel/linux/iostat/device/dm-0/r_await": {},
                "/intel/linux/iostat/device/dm-0/r_per_sec": {},
                "/intel/linux/iostat/device/dm-0/rkB_per_sec": {},
                "/intel/linux/iostat/device/dm-0/rrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-0/w_await": {},
                "/intel/linux/iostat/device/dm-0/w_per_sec": {},
                "/intel/linux/iostat/device/dm-0/wkB_per_sec": {},
                "/intel/linux/iostat/device/dm-0/wrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-1/%util": {},
                "/intel/linux/iostat/device/dm-1/await": {},
                "/intel/linux/iostat/device/dm-1/r_await": {},
                "/intel/linux/iostat/device/dm-1/r_per_sec": {},
                "/intel/linux/iostat/device/dm-1/rkB_per_sec": {},
                "/intel/linux/iostat/device/dm-1/rrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-1/w_await": {},
                "/intel/linux/iostat/device/dm-1/w_per_sec": {},
                "/intel/linux/iostat/device/dm-1/wkB_per_sec": {},
                "/intel/linux/iostat/device/dm-1/wrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-2/%util": {},
                "/intel/linux/iostat/device/dm-2/await": {},
                "/intel/linux/iostat/device/dm-2/r_await": {},
                "/intel/linux/iostat/device/dm-2/r_per_sec": {},
                "/intel/linux/iostat/device/dm-2/rkB_per_sec": {},
                "/intel/linux/iostat/device/dm-2/rrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-2/w_await": {},
                "/intel/linux/iostat/device/dm-2/w_per_sec": {},
                "/intel/linux/iostat/device/dm-2/wkB_per_sec": {},
		"/intel/linux/iostat/device/dm-1/%util": {},
                "/intel/linux/iostat/device/dm-1/await": {},
                "/intel/linux/iostat/device/dm-1/r_await": {},
                "/intel/linux/iostat/device/dm-1/r_per_sec": {},
                "/intel/linux/iostat/device/dm-1/rkB_per_sec": {},
                "/intel/linux/iostat/device/dm-1/rrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-1/w_await": {},
                "/intel/linux/iostat/device/dm-1/w_per_sec": {},
                "/intel/linux/iostat/device/dm-1/wkB_per_sec": {},
                "/intel/linux/iostat/device/dm-1/wrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-2/%util": {},
                "/intel/linux/iostat/device/dm-2/await": {},
                "/intel/linux/iostat/device/dm-2/r_await": {},
                "/intel/linux/iostat/device/dm-2/r_per_sec": {},
                "/intel/linux/iostat/device/dm-2/rkB_per_sec": {},
                "/intel/linux/iostat/device/dm-2/rrqm_per_sec": {},
                "/intel/linux/iostat/device/dm-2/w_await": {},
                "/intel/linux/iostat/device/dm-2/w_per_sec": {},
                "/intel/linux/iostat/device/dm-2/wkB_per_sec": {},
                "/intel/linux/iostat/device/dm-2/wrqm_per_sec": {},
                "/intel/linux/iostat/device/sda/%util": {},
                "/intel/linux/iostat/device/sda/await": {},
                "/intel/linux/iostat/device/sda/r_await": {},
                "/intel/linux/iostat/device/sda/r_per_sec": {},
                "/intel/linux/iostat/device/sda/rkB_per_sec": {},
                "/intel/linux/iostat/device/sda/rrqm_per_sec": {},
                "/intel/linux/iostat/device/sda/w_await": {},
                "/intel/linux/iostat/device/sda/w_per_sec": {},
                "/intel/linux/iostat/device/sda/wkB_per_sec": {},
                "/intel/linux/iostat/device/sda/wrqm_per_sec": {},
                "/intel/linux/iostat/device/sda1/%util": {},
                "/intel/linux/iostat/device/sda1/await": {},
                "/intel/linux/iostat/device/sda1/r_await": {},
                "/intel/linux/iostat/device/sda1/r_per_sec": {},
                "/intel/linux/iostat/device/sda1/rkB_per_sec": {},
                "/intel/linux/iostat/device/sda1/rrqm_per_sec": {},
                "/intel/linux/iostat/device/sda1/w_await": {},
                "/intel/linux/iostat/device/sda1/w_per_sec": {},
                "/intel/linux/iostat/device/sda1/wkB_per_sec": {},
                "/intel/linux/iostat/device/sda1/wrqm_per_sec": {},
                "/intel/linux/iostat/device/sda2/%util": {},
                "/intel/linux/iostat/device/sda2/await": {},
                "/intel/linux/iostat/device/sda2/r_await": {},
                "/intel/linux/iostat/device/sda2/r_per_sec": {},
                "/intel/linux/iostat/device/sda2/rkB_per_sec": {},
                "/intel/linux/iostat/device/sda2/rrqm_per_sec": {},
                "/intel/linux/iostat/device/sda2/w_await": {},
                "/intel/linux/iostat/device/sda2/w_per_sec": {},
                "/intel/linux/iostat/device/sda2/wkB_per_sec": {},
                "/intel/linux/iostat/device/sda2/wrqm_per_sec": {},
                "/intel/procfs/disk/*/io_time": {},
                "/intel/procfs/disk/*/merged_read": {},
                "/intel/procfs/disk/*/merged_write": {},
                "/intel/procfs/disk/*/octets_read": {},
                "/intel/procfs/disk/*/octets_write": {},
                "/intel/procfs/disk/*/ops_read": {},
                "/intel/procfs/disk/*/ops_write": {},
                "/intel/procfs/disk/*/pending_ops": {},
                "/intel/procfs/disk/*/time_read": {},
                "/intel/procfs/disk/*/time_write": {},
                "/intel/procfs/disk/*/weighted_io_time": {}
	    },
            "config": {
		"/intel/procfs/disk": {
                    "proc_path": "/proc"
                },
		"/intel/linux/iostat": {
                    "ReportSinceBoot": false
                }
            },
            "process": [
                {
                    "plugin_name": "passthru",
                    "process": null,
                    "publish": [
                        {                         
                            "plugin_name": "file",
			    "version": 1,
                            "config": {
                                "file": "/home/jasantos/psutil_disk_iostat_select.json"
                            }
                        }
                    ],
                    "config": null
                }
            ],
            "publish": null
        }
    }
}
```

**Comment by IRCody** [comment]
@juliasantos: Can you include which version of Snap you were using?

 Looking at it really quick it seems to be panic'ing [here](https://github.com/intelsdi-x/snap/blob/b508b3166d969c1d9913c4a92623cabe01242e5d/pkg/ctree/tree.go#L167). In master there is a check that the length is not 0 before we index in to the array [here](https://github.com/intelsdi-x/snap/blob/master/pkg/ctree/tree.go#L194). This change was introduced [here](https://github.com/intelsdi-x/snap/commit/6a8ba3a048f9d8ba676f813a26ba9f998e439be8). I'm not sure if the entire issue is this or if there is more to it.

**Comment by juliasantos** [comment]
We installed the latest package on github this week - v0.14.0 beta.

**Comment by thomastaylor312** [comment]
@juliasantos I think @IRCody is right. I just checked against master and the task worked. I'll work offline with you to verify

**Comment by thomastaylor312** [comment]
@juliasantos and I tried it with master and verified it worked. Closing issue.
