### ISSUE TITLE
Wildcards lacks syntax error handling

### ISSUE THREAD

**Issue by lmroz** [intelsdi-x/snap#1115]
https://github.com/intelsdi-x/snap/blob/master/control/metrics.go#L301
It's possible to create such task manifest that queries are translated to invalid regexps (like `/intel(foo`), this causes (recovered) panic in snapd.

**Comment by katarzyna-z** [comment]
I reproduced the issue using the following [commit](https://github.com/intelsdi-x/snap/commit/4833736f46f62be6729e31bb63ed003b1acef1a3). I tested snapd with snap-plugin-collector-mock2 using this task manifest:

```
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "max-failures": 10,
    "workflow": {
        "collect": {
            "metrics": {
                "/intel/(foo" : {}
            },
            "config": {
                "/intel/mock": {
                    "name": "root",
                    "password": "secret"
                }
            },
            "process": null,
            "publish": null
        }
    }
}
```
In this test I received following output from snapctl:
```
Using task manifest to create task
Error creating task:Unknown API response: invalid character 'P' looking for beginning of value

 Received: PANIC: regexp: Compile(`^intel[.](foo$`): error parsing regexp: missing closing ): `^intel[.](foo$`
goroutine 127 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x7fc22a6a23d0, 0xc8201d7980, 0xc82017aea0)
	/home/kzab/work/src/github.com/codegangsta/negroni/recovery.go:34 +0xe9
panic(0xb7ea20, 0xc8201ef430)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
regexp.MustCompile(0xc8201ef3d0, 0xe, 0x1)
	/usr/local/go/src/regexp/regexp.go:232 +0x16f
github.com/intelsdi-x/snap/control.(*metricCatalog).addItemToMatchingMap(0xc820017f80, 0xc8201ef3a0, 0xa)
	/home/kzab/work/src/github.com/intelsdi-x/snap/control/metrics.go:301 +0x182
github.com/intelsdi-x/snap/control.(*metricCatalog).MatchQuery(0xc820017f80, 0xc8202b0c60, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kzab/work/src/github.com/intelsdi-x/snap/control/metrics.go:273 +0xe4
github.com/intelsdi-x/snap/control.(*pluginControl).MatchQueryToNamespaces(0xc820123970, 0xc8202b0c60, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/
```

I was trying to reproduce the issue also with the latest snap ([commit](https://github.com/intelsdi-x/snap/commit/8fc745c1e655596904046258efa18548f2268413)) but the issue does not appear. I received the following output from snapctl:
```
Using task manifest to create task
Error creating task:Metric not found: /intel/(foo (version: 0)
```

@intelsdi-x/snap-maintainers Could you close this issue?
