### ISSUE TITLE
`$` as a separator in the task manifest causes panic

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap#1550]
`$` as a separator in the task manifest causes panic. Recovery mechanism works and Snap still works but unexpected error occurs.

Step to reproduce:
1. Run Snap
2. Load plugin
3. Create a task manifest with separator set a `$`, for example:
```
{
  "version": 1,
  "schedule": {
    "type": "simple",
    "interval": "1s"
  },
  "workflow": {
    "collect": {
      "metrics": {
        "$intel$procfs$cpu$*$active_jiffies": {}
      }
    }
  }
}
```

Current state:
```
snaptel task create -t task.json 
Using task manifest to create task
Error creating task:Unknown API response: invalid character 'P' looking for beginning of value

 Received: PANIC: runtime error: index out of range
goroutine 49 [running]:
github.com/intelsdi-x/snap/vendor/github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7f6134e0b110, 0xc4201c8f40, 0xc4203059a0)
	/home/kujawka/.gvm/pkgsets/go1.7/global/src/github.com/intelsdi-x/snap/vendor/github.com/urfave/negroni/recovery.go:34 +0xf2
panic(0xad9be0, 0xc420010120)
	/home/kujawka/.gvm/gos/go1.7/src/runtime/panic.go:458 +0x243
github.com/intelsdi-x/snap/control.(*mttNode).search(0xc4201b3440, 0xf67298, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf67298, 0x0)
	/home/kujawka/.gvm/pkgsets/go1.7/global/src/github.com/intelsdi-x/snap/control/mttrie.go:296 +0x180
github.com/intelsdi-x/snap/control.(*mttNode).GetMetrics(0xc4201b3440, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa2b000, 0x8, 0xc19ae0, 0x4)
	/home/kujawka/.gvm/pkgsets/go1.7/global/src/github.com/intelsdi-x/snap/control/mttrie.go:201 +0xc4
github.com/intelsdi-x/snap/control.(*metricCatalog).GetMetrics(0xc4201bcd80, 0xf67298, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ku
```

Expected state:
Panic does not exist. Error message is returned.

**Comment by rashmigottipati** [comment]
Great catch, @katarzyna-z . Is it in the scope of #1551 to handle illegal namespace separators other than $ in the task manifest?

**Comment by katarzyna-z** [comment]
#1551 is to protect against `index out of range` error. Other errors connected with namespace separator are returned by unmarshalling, for  `$` namespace was empty and Snap wasn't prepared for this case.  $ in task manifest indicates env variables. If variables are not set then namespace is empty.

**Comment by rashmigottipati** [comment]
Thanks for clarifying @katarzyna-z
