### ISSUE TITLE
Tribe test fails: `memberlist: Error accepting TCP connection: accept tcp 127.0.0.1:55246: accept: too many open files`

### ISSUE THREAD

**Issue by nqn** [intelsdi-x/snap#491]
```
/Library/Developer/CommandLineTools/usr/bin/make test
export PULSE_PATH=`pwd`/build; bash -c "./scripts/test.sh"
gofmt
goimports
go vet
?       github.com/intelsdi-x/pulse     [no test files]
?       github.com/intelsdi-x/pulse/cmd/pulsectl        [no test files]
ok      github.com/intelsdi-x/pulse/control     19.362s coverage: 61.5% of statements
ok      github.com/intelsdi-x/pulse/control/plugin      10.768s coverage: 70.2% of statements
ok      github.com/intelsdi-x/pulse/control/plugin/client       1.774s  coverage: 43.8% of statements
ok      github.com/intelsdi-x/pulse/control/plugin/cpolicy      0.019s  coverage: 60.8% of statements
?       github.com/intelsdi-x/pulse/control/plugin/encoding     [no test files]
ok      github.com/intelsdi-x/pulse/control/plugin/encrypter    1.343s  coverage: 65.1% of statements
?       github.com/intelsdi-x/pulse/control/routing     [no test files]
?       github.com/intelsdi-x/pulse/core        [no test files]
ok      github.com/intelsdi-x/pulse/core/cdata  0.012s  coverage: 59.1% of statements
?       github.com/intelsdi-x/pulse/core/control_event  [no test files]
?       github.com/intelsdi-x/pulse/core/ctypes [no test files]
?       github.com/intelsdi-x/pulse/core/perror [no test files]
?       github.com/intelsdi-x/pulse/core/scheduler_event        [no test files]
............................................time="2015-11-11T18:03:17-08:00" level=error msg="error enabling task" _block=enable-task _error="Task must be disabled" _module=scheduler task-id=2e696841-b5d9-4020-bcb8-3aa6db61fbfc 
..
46 total assertions

2015/11/11 18:03:17 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:55236
2015/11/11 18:03:17 [DEBUG] memberlist: TCP connection from: 127.0.0.1:60997
2015/11/11 18:03:17 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:55236
2015/11/11 18:03:17 [DEBUG] memberlist: TCP connection from: 127.0.0.1:60998
2015/11/11 18:03:17 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:55236
2015/11/11 18:03:17 [DEBUG] memberlist: TCP connection from: 127.0.0.1:60999
2015/11/11 18:03:17 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:55236
2015/11/11 18:03:17 [DEBUG] memberlist: TCP connection from: 127.0.0.1:61000
...............................time="2015-11-11T18:03:19-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=mock1 plugin_type=collector plugin_version=1 
time="2015-11-11T18:03:19-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=mock1 type=collector version=1 
time="2015-11-11T18:03:19-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
..time="2015-11-11T18:03:20-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=mock1 type=collector version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:20-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=mock1 plugin_type=collector plugin_version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=mock1 type=collector version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:20-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=mock1 plugin_type=collector plugin_version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=mock1 type=collector version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:20-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=mock1 plugin_type=collector plugin_version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=mock1 type=collector version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:20-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=mock1 plugin_type=collector plugin_version=1 
time="2015-11-11T18:03:20-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=file plugin_type=publisher plugin_version=3 
time="2015-11-11T18:03:20-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:20-08:00" level=error msg="loaded plugin.. looking for file 3 publisher" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:20-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
......time="2015-11-11T18:03:20-08:00" level=error msg="Handling task create event" _block=HandleGomitEvent _module=tribe event=Scheduler.TaskCreated task_id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 task_start_on_create=false 
time="2015-11-11T18:03:20-08:00" level=error msg="received task work" _block=start _module=worker task=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 worker=3 
........time="2015-11-11T18:03:21-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:21-08:00" level=error msg="received task work" _block=start _module=worker task=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 worker=1 
time="2015-11-11T18:03:21-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="received task work" _block=start _module=worker task=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 worker=1 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:21-08:00" level=error msg="received task work" _block=start _module=worker task=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 worker=1 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="received task work" _block=start _module=worker task=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 worker=2 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
.....time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:21-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for file 3 publisher" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:22-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=file plugin_type=publisher plugin_version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for file 3 publisher" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:22-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=file plugin_type=publisher plugin_version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for file 3 publisher" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker 
time="2015-11-11T18:03:22-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=file plugin_type=publisher plugin_version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="Handling task create event" _block=HandleGomitEvent _module=tribe event=Scheduler.TaskCreated task_id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 task_start_on_create=false 
time="2015-11-11T18:03:22-08:00" level=error msg="Handling task create event" _block=HandleGomitEvent _module=tribe event=Scheduler.TaskCreated task_id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 task_start_on_create=false 
time="2015-11-11T18:03:22-08:00" level=error msg="error getting task" _block=get-task _error="Task not found" _module=scheduler task-id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 
time="2015-11-11T18:03:22-08:00" level=error msg="Handling task create event" _block=HandleGomitEvent _module=tribe event=Scheduler.TaskCreated task_id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 task_start_on_create=false 
2015/11/11 18:03:22 http: Accept error: accept tcp [::]:55237: accept: too many open files; retrying in 5ms
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for mock1 1 collector" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="loaded plugin.. looking for file 3 publisher" _module=worker name=file type=publisher version=3 
time="2015-11-11T18:03:22-08:00" level=error msg="Plugin already loaded" _block=isPluginLoaded _module=worker time="2015-11-11T18:03:22-08:00" level=error msg="Handling load plugin event" _block=HandleGomitEvent _module=tribe event=Control.PluginLoaded plugin_name=file plugin_type=publisher plugin_version=3 
time="2015-11-11T18:03:23-08:00" level=error msg="Handling task create event" _block=HandleGomitEvent _module=tribe event=Scheduler.TaskCreated task_id=683e2fb4-4b9d-4838-b7b9-050ce2c02e27 task_start_on_create=false 
.
99 total assertions

2015/11/11 18:03:23 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:55246
2015/11/11 18:03:23 [DEBUG] memberlist: TCP connection from: 127.0.0.1:61156
2015/11/11 18:03:23 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:55246
2015/11/11 18:03:23 [ERR] memberlist: Error accepting TCP connection: accept tcp 127.0.0.1:55246: accept: too many open files
time="2015-11-11T18:03:23-08:00" level=error msg="Failed to join tribe" _block=New _module=tribe addr=127.0.0.1 name=member-55249 port=55250 seed="127.0.0.1:55246" 
--- FAIL: TestTribePluginAgreements (0.00s)
panic: Failed to join tribe [recovered]
        panic: Failed to join tribe

goroutine 865 [running]:
testing.tRunner.func1(0xc8201ecea0)
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:450 +0x171
github.com/intelsdi-x/pulse/mgmt/rest.startTribes(0x5, 0x0, 0x0, 0x0)
        /Users/nqnielse/workspace/go/src/github.com/intelsdi-x/pulse/mgmt/rest/tribe_test.go:550 +0x4ab
github.com/intelsdi-x/pulse/mgmt/rest.TestTribePluginAgreements(0xc8201ecea0)
        /Users/nqnielse/workspace/go/src/github.com/intelsdi-x/pulse/mgmt/rest/tribe_test.go:298 +0xad
testing.tRunner(0xc8201ecea0, 0xa597d0)
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x84b448, 0xa597a0, 0x3, 0x3, 0xc820120301)
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc821719ef8, 0xa617e0)
        /usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:494 +0x70
main.main()
        github.com/intelsdi-x/pulse/mgmt/rest/_test/_testmain.go:118 +0x252

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by danielscottt** [comment]
This can be resolved by increasing the number of file descriptors which can be open via `ulimit`.  I don't believe there is another way, as I don't think we should make changes to a system via our test scripts.

**Comment by lynxbat** [comment]
Should we catch this error better and suggest since we can't change? Would be a massive help to a user.

**Comment by geauxvirtual** [comment]
I recently ran across this issue running tests on my local machine. While raising the `ulimit` would suffice, or starting a new terminal session (on Macs, default file limit is 256), this blog post may shed some light that it may be the Rest API not closing the connection properly when loading plugins http://craigwickesser.com/2015/01/golang-http-to-many-open-files/. It may be worth investigating more.

**Comment by lynxbat** [comment]
Closing this since @nqn verified offline it can be closed.
